export const FETCH_CONTENTS = 'FETCH_CONTENTS'
export const FETCH_CONTENTS_SUCCESS = 'FETCH_CONTENTS_SUCCESS'
export const FETCH_CONTENTS_FAILURE = 'FETCH_CONTENTS_FAILURE'

export const GET_COORDINATES = 'GET_COORDINATES'
export const GET_COORDINATES_SUCCESS = 'GET_COORDINATES_SUCCESS'
export const GET_COORDINATES_FAILURE = 'GET_COORDINATES_FAILURE'
